const breeds = [
    { title: "None" },
    { title: "Abyssinian" },
    { title: "Aegean" },
    { title: "American Bobtail" },
    { title: "Americal Curl" },
    { title: "American Shorthair" },
    { title: "American Wirehair" },
    { title: "Arabian Mau" },
    { title: "Austrilian Mist" },
    { title: "Balinese" },
    { title: "Bambino" },
    { title: "Bengal" },
    { title: "Birman" },
    { title: "Bombay" },
    { title: "British Longhair" },
    { title: "British Shorthair" },
    { title: "Burmese" },
    { title: "Burmilla" },
    { title: "California Spangled" },
    { title: "Chantilly-Tiffany" },
    { title: "Chartreux" },
    { title: "Chausie" },
    { title: "Cheetoh" },
    { title: "Colorpoint Shorthair" },
    { title: "Cornish Rex" },
    { title: "Cymric" },
    { title: "Cyprus" },
    { title: "Devon Rex" },
    { title: "Donskoy" },
    { title: "Dragon Li" },
    { title: "Egyptian Mau" },
    { title: "European Burmese" },
    { title: "Exotic Shorthair" },
    { title: "Havana Brown" },
    { title: "Himalayan" },
    { title: "Japanese Bobtail" },
    { title: "Javanese" },
    { title: "Khao Manee" },
    { title: "Korat" },
    { title: "Kurilian" },
    { title: "LaPerm" },
    { title: "Maine Coon" },
    { title: "Malayan" },
    { title: "Manx Munchkin" },
    { title: "Nebelung" },
    { title: "Norwegian Forest Cat" },
    { title: "Ocicat" },
    { title: "Oriental" },
    { title: "Persian" },
    { title: "Pixie-bob" },
    { title: "Regamuffin" },
    { title: "Ragdoll" },
    { title: "Russian Blue" },
    { title: "Savannah" },
    { title: "Scottish Fold" },
    { title: "Selkirk Rex" },
    { title: "Siamese" },
    { title: "Siberian" },
    { title: "Singapura" },
    { title: "Snowshoe" },
    { title: "Somali" },
    { title: "Sphynx" },
    { title: "Tonkinese" },
    { title: "Toyger" },
    { title: "Turkish Angora" },
    { title: "Turkish Van" },
    { title: "York Chocolate" }

]

export { breeds };
